# Generated by Django 3.2.9 on 2021-12-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0004_remove_product_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
